### ISSUE TITLE
抓虫日记：etcd为何会连接不上

### ISSUE THREAD

**Issue by andyblog** [k8s-club/k8s-club#42]
看了抓虫日记里面的内容，整个出问题的流程为：apiserver连接不上etcd，然后apiserver触发协程泄漏的问题，继而oom，
但是apiserver连接不上etcd的原因是什么，是etcd出什么问题了吗

**Comment by sxllwx** [comment]
Etcd集群当时出现了网络抖动，不断进行leader-election

**Comment by andyblog** [comment]
收到，感谢
