### ISSUE TITLE
在掌握 K8s 路上，应该理解下面这些 QA？

### ISSUE THREAD

**Issue by yxxhero** [k8s-club/k8s-club#6]
大佬。这些问题的答案在哪里，我想学习参考一下。
https://github.com/astraw99/K8s-club/blob/master/QA%20to%20Understand%20K8s.md

**Comment by astraw99** [comment]
谢谢关注，目前在资料整理中，更新了告知~

**Comment by astraw99** [comment]
@yxxhero @sxllwx 相关问题已整理更新，理解可能有误，欢迎指正交流~

**Comment by yxxhero** [comment]
@astraw99 Thanks very much.
